site:
    title: "koalcat"
    subtitle: "..."
    limit: 10
    theme: theme
    lang: zh
    url: "http://www.koalcat.tk"
    comment: username
    logo: "-/images/koalcat.jpg"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    xuchdeid:
        name: "xuchdeid"
        intro: "cat"
        avatar: "-/images/xuchdeid.jpeg"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "update"
        git push origin
